DELETE FROM TB_MYTEST;

DELETE FROM TT_USER;
INSERT INTO TT_USER (NAME, AGE) VALUES ('AAA', '100');
INSERT INTO TT_USER (NAME, AGE) VALUES ('BBB', '100');
INSERT INTO TT_USER (NAME, AGE) VALUES ('CCC', '100');